site_name: Bluz Docs
site_favicon: /img/bluz_only_logo.png
pages:
- Home: index.md
- Tutorials:
  - 'Getting Started': tutorials/getting_started.md
  - 'Gateway/Gateway Shield Setup': tutorials/gateway_getting_started.md
  - 'Operating States': tutorials/states.md
  - 'Loading Firmware': tutorials/updates.md
  - 'Talking Serial': tutorials/serial.md
  - 'Gateway/DK Interactions': tutorials/gateway_dk_interactions.md
  - 'Local Communication': tutorials/local_communication.md
  - 'Bootloader Updating': tutorials/bootloader.md
  - 'Building with Bluz': tutorials/custom_hw.md
  - 'Low Power Optimizations': tutorials/low_power.md
- Reference:
  - 'Bluetooth LE': reference/ble.md
  - 'Beacon': reference/beacon.md
  - 'Cloud Functions': reference/cloud.md
  - 'Input/Output': reference/io.md
  - 'Interrupts': reference/interrupts.md
  - 'Serial': reference/serial.md
  - 'SPI': reference/spi.md
  - 'TWI/I2C/Wire': reference/wire.md
  - 'System': reference/system.md
  - 'String': reference/string.md
  - 'RGB': reference/rgb.md
  - 'EEPROM': reference/eeprom.md
  - 'Time': reference/time.md
  - 'Software Timers': reference/timer.md
  - 'Servo': reference/servo.md
  - 'Bluz Gateway': reference/bluz_gateway.md
- Hardware:
  - 'Bluz DK': hardware/dk.md
  - 'CR2032 Battery Shield': hardware/battery.md
  - 'Gateway Shield': hardware/gw_shield.md
  - 'Gateway': hardware/gw.md
  - 'UART Shield': hardware/uart_shield.md
  - 'J-Link Shield': hardware/jlink.md
- Troubleshooting:
  - "SOS Codes": troubleshooting/sos.md
extra_css:
    - css/styles.css
